import Test.Alert
import Test.Block
import Test.Certificate
import Test.ChangeCipher
import Test.CipherSuite
import Test.ClientCertificateType
import Test.CompressionMethod
import Test.DiffieHellman
import Test.DistinguishedName
import Test.Encryptor
import Test.Framework.Runners.Console
import Test.Handshake
import Test.HashAlgorithm
import Test.HybridEncrypt
import Test.HMAC
import Test.PRF
import Test.ProtocolVersion
import Test.Random
import Test.RC4
import Test.Records
import Test.Session
import Test.SignatureAlgorithm
import Test.Stream
import Test.TorCell
import Test.TripleDES
import Test.Word24
import Test.Zlib

main :: IO ()
main =
  defaultMain [
    torCellTests
  , word24Tests
  , zlibTests
  , alertTests
  , blockTests
  , certificateTests
  , changeCipherTests
  , cipherSuiteTests
  , clientCertificateTypeTests
  , compressionMethodTests
  , diffieHellmanTests
  , distinguishedNameTests
  , encryptorTests
  , hmacTests
  , handshakeTests
  , hashAlgorithmTests
  , hybridEncryptionTest
  , prfTests
  , protocolVersionTests
  , rc4Tests
  , randomTests
  , recordsTests
  , sessionTests
  , signatureAlgorithmTests
  , streamTests
  , tripleDESTests
  ]
